logging:
  level:
    #root: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trocaIdioma
    username: postgres
    password: 1234
  jpa:
    hibernate:
      #ddl-auto: create-drop
      #ddl-auto: none
      #ddl-auto: validate
      ddl-auto: update
  session:
    store-type: jdbc
    timeout: 1200
